### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by Martmists-GH** [IzunaDevs/DBank#2]
- [ ] Fucking **everything**
- [ ] Dynamic exchange rates
- [ ] User-based wallets
- [ ] $aving up using a bank account
- [ ] API for bots to query
- [ ] User UI on webpage
